project:
  type: website

website:
  title: "Open Time Series Initiative"
  search: false
  page-navigation: false
  navbar:
    collapse-below: lg
    background: light
    pinned: false
    left:
       - href: empty.qmd
    #    text: Home
     # - about.qmd
    tools:
      - icon: github
        href: https://github.com/opentsi

  

format:
  html:
    theme: lightly
    css: styles.css
    code-copy: true
    code-overflow: wrap



