---
pagetitle: "Open Time Series Initiative"
page-layout: custom
section-divs: true
toc: false
css: index.css
editor: source
---



::: {.content-block}

::: {.grid}
::: {.g-col-7}

## Human-Friendly, Machine-Readable.

The Open Time Series Initiative derives scientific-grade time series from data publications for the broader public. 
In addition to data, we share an inclusive, battle-tested framework for ingestion of publicly available data and vintage management.

::: {.hero-buttons}
[GitHub Organization](https://github.com/opentsi){.btn-action-primary .btn-action .btn .btn-success .btn-lg role="button"}
:::

:::

::: {.g-col-5}

<br /><br />

```{r, eval=FALSE}
library(opentimeseries)
library(tsbox)
b202307 <- archive_read(
    "ch.kof.globalbaro.incident",
    remote_archive = "opentsi/kofethz",
    date = "2023-07-01"
)
b202407 <- archive_read(
    "ch.kof.globalbaro.incident",
    remote_archive = "opentsi/kofethz",
    date = "2024-07-01"
)
ts_plot(rbind(b202307, b202407))

```

:::

:::

<!-- End of first grid  -->

<!-- Content Block End  -->
:::




::: {.content-block}


### Versioned Time Series for Researchers

Open Time Series archives use remote git repositories as backends to deliver real-time data. 

::: {.features} 
::: {.feature}

### Real Time Vintages & Full History

Get the state of revised time series at time of their publication.
Compare revisions and benchmark your forecasts using complete history triangles. 



:::

::: {.feature}

### REST API 

Directly load data into your favorite data science environments without downloading additional software.


:::


::: {.feature}

### Multi-Lingual Meta Information 
Proven in German, French and Italian speaking Switzerland: csv+json two file approach to handle multi-lingual meta information alongside time series data.  



:::


::: {.feature}

### Inclusive to Encourage Reuse 
Reuse the open time series approach to create your own, reliable time series archive and data ingestion routines.


:::




::: {.feature}

### Sustainable through Lite Weight
Use GitHub as a freely and readily available backend for your time series archives. 


:::




::: {.feature}

### Rich Proof of Concept

Benefit from multi-year experience of the Swiss Economic using the open time series approach to source and manage public time series data.


:::



<!-- Feature Block End  -->
:::




<!-- Content Block End  -->
:::


::: {.button-background}

::: {.content-block}


::: {.grid}

::: {.g-col-4}

:::


::: {.g-col-4}

[Follow our journey](https://kof.ethz.ch/en/the-institute/kof-divisions/research-division-kof-lab/rseed/subscription.html){.btn-action-primary  .btn-action .btn .btn-success .btn-lg role="button" style="margin-top: 1em;"}

<br />
<br />

:::

::: {.g-col-4}

:::

:::

:::

:::


::: {.alt-background}

::: {.content-block}


::: {.grid}

::: {.g-col-4}




:::

::: {.g-col-4}

#### ETH Zurich

[Research Software Engineering and Economic Data (RSEED)](https://rseed.ch)

[KOF Lab](https://kof.ethz.ch/en/the-institute/kof-divisions/research-division-kof-lab/rseed.html)

[Join our newsletter!](https://kof.ethz.ch/en/the-institute/kof-divisions/research-division-kof-lab/rseed/subscription.html)


#### Contact Us

Minna Heim

heim [ at ] kof.ethz.ch


:::


::: {.g-col-4}

#### GitHub

[Open Time Series GitHub organization](https://github.com/opentsi)

[opentimeseries R package development](https://github.com/opentsi/opentimeseries)) 

:::



<!-- Grid End  -->
:::


:::

:::






